// 位置情報etc
var datas = {
    /*'tokurenji': {
        lat:35.115231,
        lng:136.646914,
        name: 'スポット名',
        cat: '小分類',
        cid: ['history','station','bathroom','gourmet','lives','view'], // 第１カテゴリを一番前に記述
        addr: '三重県桑名市多度町下野代3171',
        tel: '0594-48-6572', 
        time: '営業時間', 
        closed: '定休日', 
        park: '駐車場',
        img: './js/config/画像.jpg',
        url: 'http://ブログのURL'
    },*/
    'ootoriihaisui': {
        lat:35.116617,
        lng:136.663509,
        name: '大鳥居排水機場',
        cat: 'ポンプ場',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町大鳥居',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'noshirohaisui': {
        lat:35.120859,
        lng:136.664728,
        name: '野代排水機場',
        cat: 'ポンプ場',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町大鳥居',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'hachiman2': {
        lat:35.132188,
        lng:136.664516,
        name: '八幡神社',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町南之郷',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'hachiman1': {
        lat:35.118291,
        lng:136.658779,
        name: '八幡神社',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町大鳥居',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'nakasutemple': {
        lat:35.132070,
        lng:136.657684,
        name: '中須神社',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町中須',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'satomuranouen': {
        lat:35.131453,
        lng:136.662187,
        name: '里邨園芸',
        cat: 'ビニルハウス',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町南之郷',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'itounouen': {
        lat:35.131338,
        lng:136.656163,
        name: '伊藤農園',
        cat: 'ビニルハウス',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町中須',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'kataokanouen': {
        lat:35.123222,
        lng:136.654795,
        name: '片岡農園',
        cat: 'ビニルハウス',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町大鳥居',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'matsunagaGS': {
        lat:35.116106,
        lng:136.652322,
        name: '松永石油',
        cat: 'ガソリンスタンド',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町下野代617-1',
        tel: '0594-48-5211', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'ministop1': {
        lat:35.114471,
        lng:136.653031,
        name: 'ミニストップ多度町店',
        cat: 'コンビニ',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町下野代574-1',
        tel: '0594-48-6101', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'cafetowa': {
        lat:35.117995,
        lng:136.651609,
        name: '喫茶「とわ」',
        cat: '飲食店',
        cid: ['gourmet','bathroom'],
        addr: '三重県桑名市多度町下野代',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'ichibantei': {
        lat:35.119731,
        lng:136.651705,
        name: '熱烈一番亭多度店',
        cat: '飲食店',
        cid: ['gourmet','bathroom'],
        addr: '三重県桑名市多度町下野代1132−4',
        tel: '0594-49-3500', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'seven1': {
        lat:35.119691,
        lng:136.650913,
        name: 'セブンイレブン桑名多度下野代店',
        cat: 'コンビニ',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町下野代出口1039',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'daiwa': {
        lat:35.118354,
        lng:136.649161,
        name: '大和',
        cat: '飲食店',
        cid: ['gourmet','bathroom'],
        addr: '三重県桑名市多度町下野代712',
        tel: '0594-48-3751', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'italianmoto': {
        lat:35.118905,
        lng:136.648112,
        name: 'イタリアン「モトリーノ」',
        cat: '飲食店',
        cid: ['gourmet','bathroom'],
        addr: '三重県桑名市多度町下野代897',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'cafetime': {
        lat:35.118661,
        lng:136.647757,
        name: '喫茶「タイム」',
        cat: '喫茶店',
        cid: ['gourmet','bathroom'],
        addr: '三重県桑名市多度町下野代895',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'myoutaiji': {
        lat:35.119108,
        lng:136.656339,
        name: '妙体寺',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'nousonkouen': {
        lat:35.117223,
        lng:136.658515,
        name: '大鳥居農村公園',
        cat: '公園',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町大鳥居30',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'inryouji': {
        lat:35.116660,
        lng:136.660019,
        name: '因領寺',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町大鳥居49',
        tel: '0594-48-3175', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'enjuji': {
        lat:35.126868,
        lng:136.655422,
        name: '円寿寺',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町中須1258',
        tel: '0594-48-3021', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'teikenkougyou': {
        lat:35.124477,
        lng:136.654265,
        name: '定建工業',
        cat: '建設会社',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町下野代1387',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'tadoEESchool': {
        lat:35.120238,
        lng:136.648564,
        name: '多度東小学校',
        cat: '学校',
        cid: ['bathroom'],
        addr: '三重県桑名市多度町下野代955',
        tel: '0594-48-2322', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'noshiritemple': {
        lat:35.118463,
        lng:136.645747,
        name: '野志里神社',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町下野代',
        tel: '', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'engyouji': {
        lat:35.117121,
        lng:136.645714,
        name: '延柳寺',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市下野代3101',
        tel: '0594-48-3240', 
        time: '', 
        closed: '', 
        park: '',
        img: '',
    },
    'tokurenji': {
        lat:35.115231,
        lng:136.646914,
        name: '徳蓮寺',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町下野代3171',
        tel: '0594-48-6572', 
        time: '', 
        closed: '', 
        park: 'あり',
        img: '',
    },
    'senkoubou': {
        lat:35.129172,
        lng:136.666802,
        name: '専光坊',
        cat: '寺社',
        cid: ['history','bathroom'],
        addr: '三重県桑名市多度町南之郷383', 
        tel: '0594-48-2178', 
        time: '', 
        closed: '', 
        park: '',
        img: './js/config/senkoubou.jpg',
        url: 'http://tenmie.blog.fc2.com/blog-entry-557.html'
    },
    'noshiroeki': {
        lat:35.115889,
        lng:136.647193,
        name: '下野代駅', 
        cat: '電車', 
        cid: ['station','bathroom'],
        addr: '三重県桑名市多度町下野代',
        park: 'あり',
        img: './js/config/noshiroeki.jpg'
    }
};